language: node_js
node_js: 10.15.3
script: skip
before_deploy: travis/before_deploy.sh
deploy:
  - provider: s3
    access_key_id: "AKIAZLVOUXM6CV6AIX35"
    secret_access_key: "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"
    bucket: "moonlight-client"
    skip_cleanup: true
    local_dir: client/build
    region: us-east-1
    delete: true 
    on: 
      branch: master
after_deploy: travis/after_deploy.sh