# https://docs.travis-ci.com/user/job-lifecycle/

language: node_js
node_js: 10.15.3
env:
  global:
    - AWS_CONFIG_FILE=.awsconfig
    - CYPRESS_RECORD_KEY=4be3dc17-34bf-44aa-bcea-c0a869a8d7a4

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache

install: travis/install.sh

jobs:
  include:
    - before_script: travis/before_script-branch.sh
      script: travis/script-branch.sh
      after_script: travis/after_script-branch.sh
      if: branch != master
    - env: CYPRESS_BASE_URL=https://moonlight-health.com
      before_script: travis/before_script-master.sh
      script: travis/script-master.sh
      if: branch = master
