language: node_js
node_js: 10.15.3
env:
  - AWS_CONFIG_FILE=.awsconfig
install: travis/install.sh
script: skip
before_deploy: travis/before_deploy.sh
deploy:
  provider: sript
  script: travis/deploy.sh
  skip_cleanup: true
  on: 
    branch: master
after_deploy: travis/after_deploy.sh