language: 
  - node_js
  - python
node_js: 10.15.3
python: 3.7
env:
  - AWS_CONFIG_FILE=.awsconfig
install: travis/install.sh
script: skip
before_deploy: travis/before_deploy.sh
deploy:
  provider: sript
  script: travis/deploy.sh
  on: 
    branch: master
after_deploy: travis/after_deploy.sh