# https://docs.travis-ci.com/user/job-lifecycle/

language: node_js
node_js: 10.15.3
env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAZLVOUXM6CV6AIX35
    - AWS_SECRET_ACCESS_KEY=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
    - AWS_DEFAULT_REGION=us-east-1
    - CYPRESS_RECORD_KEY=4be3dc17-34bf-44aa-bcea-c0a869a8d7a4

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache

install: travis/install.sh

jobs:
  include:
    - script: travis/script-branch.sh
      after_script: travis/after_script-branch.sh
      if: branch != master
    - script: travis/script-master.sh
      if: branch = master
