# https://docs.travis-ci.com/user/job-lifecycle/

language: node_js
node_js: 12.16.1
env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAZLVOUXM6HAHWSANH
    - secure: "ArftoCPDKIA7CDM6SnX9JClCfiWVuBQ8/EkSwJB5clp9Gl7vSs3kjwhiNpLR2gCMsiIZQRqa605p2FudPr0ZiEsJB/C5ZtNQ1Q/dVI1SOIN7RSKIQ7UEVzPSyOdLZ3elawL5MVYsqLn/I9prnYf8gVOFqCtfNIDW4H7UgYpAtESV0yrfQPpVOVh2KUuMqukMe4smRwxGq4unn1BabhnaRsoXA2ITmRG9QCRcsGvLljnOjluhEq/VUojRGNHrGhauotcTdjCh/a/kTL89T/rpN4K1a7uE9YmOseBBxetmU8yo3JdNS+aKMpPXW2UYA9ZryUnPHjhX9szBXQU8gjDzGdy2GOA/K78f/nJTm20BusLVGDgZxHA/4JkLdDmw92xL6CQep5L4pM2csiaIuquCqFMvApwiYcDwgHzMU+81AaoMrr0yH9Yqy6SaiBVv5DvGOh23UFFNkCBZ30T/x2hbJzGWiEyfJmAxMaPXP2+Qfc45LGPFC0n0l1Al2B4bvaSims0q2rw9FrOiO5IzO2S3Z2M8tf1imgMCzyu4yymBI6haXgCBRQc84fUl7mnd1aSRlBZjpH/sPOM5Cw5chfCZA9Qg2Xoh4XzzjT6GOitNAhyBrI6QGbSjJkIchbqs5lqkcoiPQu1+SQxzaLic11gRRXNtFlcoT/HAqhAZAOegKNo="
    - AWS_DEFAULT_REGION=us-east-1
    - secure: "Mmhbhc8KHWvbtIpv6WgkkI2TlORJ3DAiqi/uO+svhZXlHjkK0v7dmHWQhpQImAEWinWudR1e4PsfVhNoGR7/cVUvVOjFSYIIWUSpawNOuxsMQ6pdJFPpEDLoMNGwokA21wdua3cwXw/3gymjUV7C5YQSQaxt2aEBziCSLBCfUF8vK8TNqcb6uaGiiB4q1kljgmhGNmrz+AswSJauEYLDD+Wli6yKuZDXH2FYD5MRUAk/Ig0CjYLW554aTCFQAdWZa2Qo505K+dHsqmxZZNMnlSIC1rJYrvwU/qscVxyyTwye+8ID/RuC9E6Udml85Gj+4c9rEKPnDF5s+YNaU9hwAckNbk35A4QjWrt8/zqcKeD3KVE752X0aXf7Ocv7NTAs3wSHhmxQ9cGa8JgPQQLUFkoqtBmHiCw8CQs6PP7yke3Sj2k9W7brPs86mJY5UEHgbnDryGSvveYW+6Vd8vkTB5gCugIbSUEQOb/XtSExwgJBRXd72+dTgAQQUYmprgQkoMdSnoVE8RPMz3sP+9SmwoLXJXV4sBCwdWzpkKwuG+GRZNbZE5LSDDIGDNd5SRLLuxR7ybNxZ4ZfslONUe9LumnNaJjy59t3iA+gtNh8f8f2DfMKyA4azSIvZzL97ndJELzsTWCvcpMF2EXgyLPViEpwDaNyDr5R3OLFybv/9UY="
    - secure: "rmUZbvISxBZM8XXBnik1claTeLPcWaBxrxnLjyz2OoJTw0hBGon9TY4Ckht+rpXejL0KLnMtdWV4YvW2iyQuvQsK/Qw97dZIj7raqUMPvyYzx1Tk1nMPUQwAXJFQ5YAUb31G7roNZJMDDDB4+ckQG4JvtPFOa0zUAUStvoPBlk3a6UY5iGYwSAz1XSL+sLpXtw2pQzMxgSHrwPmGdHPOxq16KmtD/7zSKsosPB5eEBTayPdfur0PM42Ro00IK+YDZj7G/oVZKiw9NxO0hBt9RI1xwQG4JSvNhdCXHgtsjmZxy7f63c/HVJczm7G0NxFqZmQbc8pow1b5pz9PWFu1PHZK9Npzv1QS9Fme+ooKwcuTg/Rv5EQi6+BDeaW5cQAPAhXEQqn8+H3SW6xvPNCA9Q83pJHqUnAn0zZf+LmJ037xXkoOgocaAj5mwF5humkKfgO/9lQlppiTaSJT7xY/7T8sb9w8jSfESCpsZDqb44gHl6MHIE0eRSfLbiuGdscZEU7hNhMDUMOMjzTn28PqJMimGeey+AmwhmPkb/fwLJrnxC+wSNCN0RYEEfP5mS2oVzJAlkVfbo9/WGhqJswQmmtlA/UQe5pi2hjkluyfVRv/hCWH9FjVs0VdEv3q01FEqXBcgtq5qyJXiu018+RchDx8pmeMl+1cDPyyp3jPHx4="
    - CYPRESS_RECORD_KEY=4be3dc17-34bf-44aa-bcea-c0a869a8d7a4
    - TF_CLI_CONFIG_FILE=/home/travis/.terraformrc
    - TF_IN_AUTOMATION=true
    - secure: "kFq6rd8vPr0qIujLcZEqSRlACaH4IDcU1Z0ebf1WwISulZBO5Vgh9kZOCc4QmggbMuAKAvTx3W5BAxYu6JDVVRW/awDHJ6RVfJ909xh2vKN+e/44TRD/u9ZpYnu/32sOhnRYEiZH3BbdBOBi5L03D37Mr4eK6U8KZuusX0Z9+oqYDwA8ldmaw69CCALhpE7BjlQOFBir7mrnV0TaM0QJnW88TLYEHQslyGi8lDqJ3UX8vKqToOHKsfks01UUGTT/4ShcMjLvXXhTAbruMmo9BrpkpRSRyqqFHSkuMEH3grns4WK3pYjrXJ+NgTG/9lUiEIaFcIHBviPd68I43iPndMk/d3NUPf9iR2SbEYhRM2O6dE2l/IK+bEIEie0RUfNGIXwMEqp3L3rUE9o9PzKBWEXnDiI1oIUnl5JqbSY0XD2ibfpbvuvQs409CXn3+5cAkP4PQOeUbGMjRoE0/ONvlpYlIHfGD6BEyRpZEENxbF+TS5ARw0oWT2LzfB44tdtxVj6av1GydSM1yfOPREALDtFs4EpU/ickVYGBh0U5cAOMpdj2qtSeGM8IH6YvGd1blwwyLtoBowZLnn+GfHmw1ff5gGpdXxo7gvd6sHb8jkVgB0t7T3KibLqh/8Yntxpstdr4e7btUapUltTQ6W3WDA3zAPqAZJKRMbSmThGaA78="

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache

jobs:
  fail_fast: true
  include:
    - env: TF_WORKSPACE=moonlight-health
      script: travis/script-master.sh
      if: branch = master
