import React from "react";
import styled from "styled-components";
import {
  PRIMARY_COLOR,
  PRIMARY_BACKGROUND_COLOR,
  QUARTER_OPAQUE,
  CONTENT_COLOR
} from "../styles/colors";
import PublicPage from "./PublicPage";
import PrivatePage from "./PrivatePage";
import { useUserId } from "../hooks/router";

const MainHeader = styled.h1`
  color: ${PRIMARY_COLOR};
  text-align: center;
  width: 100%;
`;

const SecondHeader = styled.h1`
  font-size: 4rem;
  color: ${CONTENT_COLOR};
  text-align: center;
`;

const Content = styled.h2`
  font-size: 3rem;
  color: ${PRIMARY_COLOR};
  text-align: center;
`;

const ContentText = styled.h3`
  color: ${CONTENT_COLOR};
  text-align: center;
`;

const ContentBlurb = styled.section`
  border-bottom: 1px solid ${CONTENT_COLOR} ${QUARTER_OPAQUE};
  border-top: 1px solid ${CONTENT_COLOR} ${QUARTER_OPAQUE};
  border-right: 1px solid ${CONTENT_COLOR} ${QUARTER_OPAQUE};
  border-left: 1px solid ${CONTENT_COLOR} ${QUARTER_OPAQUE};
  flex-direction: row;
  justify-content: space-between;
  height: 220px;
  width: 949px;
  float: left;
  background: ${PRIMARY_BACKGROUND_COLOR};
`;

const RedText = styled.h3`
  color: ${"#A52A2A"};
  text-align: center;
`;

const Background1 = styled.section`
  background: ${PRIMARY_BACKGROUND_COLOR};
  padding: 1em;
  border-bottom: 1px solid ${CONTENT_COLOR} ${QUARTER_OPAQUE};
  justify-content: space-between;
`;

const HomePageContent = () => (
  <>
    <MainHeader>MOONLIGHT HEALTH</MainHeader>

    <Background1>
      <RedText>COMPETITIVE ADVANTAGE FOR GP & ORTHODONTIC OFFICES</RedText>
      <SecondHeader>
        Put an Oral Surgeon <br></br>
        In Your Practice
      </SecondHeader>
    </Background1>

    <Content>Stop sending money out your door…</Content>
    <ContentText>
      Have you ever stopped to think how much revenue you are sending out the
      door in oral surgery referrals? <br></br>
      If your practice refers out even 5 patients a month, and that patient
      receives an average of $3,000 worth <br></br>
      of treatment, that is over $180,000 annually that the referring practice
      doesn't see a dime of.
    </ContentText>
    <ContentText>
      What if the surgeon worked for you? What if you received a portion of the
      revenue generated by your valuable <br></br>
      referrals, without having to worry about the liability, risk, and
      equipment involved in hiring a surgical associate?
    </ContentText>

    <Content>Contact Info</Content>
    <ContentText>Location: DC/MD/VA/FL</ContentText>
    <ContentText>Email: dr.patel@moonlightoralsurgery.com</ContentText>
    <ContentText>Phone: (408) 506-8919</ContentText>

    <Content>Advantages</Content>
    <ContentBlurb>
      <RedText>More Convinient</RedText>
      <ContentText>
        Our services improve the general dentist’s practice by bringing oral
        surgery <br></br>
        services directly to their patients. The ability to offer specialized
        services in- <br></br>
        house is an added layer of convenience that will only add to your
        patient’s <br></br>
        comfort and trust in your practice.
      </ContentText>
    </ContentBlurb>

    <ContentBlurb>
      <RedText>Passive Revenue</RedText>
      <ContentText>
        Stop referring patients to another provider when you could own the
        revenue <br></br>
        stream. With our unique partnership structure, the practice earns a
        passive <br></br>
        income, in form of a percentage of production, from the cases our
        surgeon <br></br>
        completes at their office.
      </ContentText>
    </ContentBlurb>

    <ContentBlurb>
      <RedText>Stress-Free</RedText>
      <ContentText>
        Practice owners do not have to concern themselves with the high costs,
        stress, <br></br>
        and responsibility of liability associated with surgical procedures.
        Moonlight <br></br>
        Oral Surgery ensures all of our surgeons are fully licensed, certified,
        and <br></br>
        equipped with everything you need.
      </ContentText>
    </ContentBlurb>

    <ContentBlurb>
      <RedText>More Freedom</RedText>
      <ContentText>
        Practice owners can book our surgeons on-demand, knowing that they will{" "}
        <br></br>
        come to your office with everything they need to perform their
        procedures. Our <br></br>
        surgeon can be equipped with their own surgical instruments and supplies
        along <br></br>
        with the necessary instrument loadout for any procedures. Unlike hiring
        an <br></br>
        associate, there is no long-term commitment. Practice owners can choose
        their <br></br>
        preferred oral surgeon when they want.
      </ContentText>
    </ContentBlurb>
  </>
);

const HomePage = () => {
  const userId = useUserId();
  return userId === 0 ? (
    <PublicPage>
      <HomePageContent />
    </PublicPage>
  ) : (
    <PrivatePage>
      <HomePageContent />
    </PrivatePage>
  );
}

export default HomePage;
