name: QA Deploy
on: pull_request

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  PROD_RDS_MASTER_USER_PASSWORD: ${{ secrets.PROD_RDS_MASTER_USER_PASSWORD }}
  QA_RDS_MASTER_USER_PASSWORD: ${{ secrets.QA_RDS_MASTER_USER_PASSWORD }}
  AWS_DEFAULT_REGION: us-east-1
  TF_CLI_CONFIG_FILE: /home/travis/.terraformrc
  TF_IN_AUTOMATION: true
  TF_WORKSPACE: env1-qa-moonlight-health

jobs:
  deploy:
    name: Deploy to QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.16.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - uses: chrislennon/action-aws-cli@v1.1
      - uses: hashicorp/setup-terraform@v1.1.0
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}
      - run: ./script-branch.sh
        working-directory: ./travis
